SilveR/Controllers/DataController.cs
using ExcelDataReader;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using SilveR.Helpers;
using SilveR.Models;
using SilveR.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace SilveR.Controllers
{
    public class DataController : Controller
    {
        private readonly ISilveRRepository repository;

        public DataController(ISilveRRepository repository)
        {
            this.repository = repository;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            ViewBag.HasDatasets = await repository.HasDatasets();

            ViewBag.InfoMessage = TempData["InfoMessage"];
            ViewBag.ErrorMessage = TempData["ErrorMessage"];

            return View();
        }

        [HttpGet]
        public async Task<ActionResult> GetDatasets()
        {
            IEnumerable<DatasetViewModel> datasets = await repository.GetDatasetViewModels();
            return Json(datasets);
        }

        [HttpGet]
        public ActionResult DataUploader()
        {
            return View("DataUploader");
        }

        //uploading a file
        [HttpPost]
        public async Task<IActionResult> DataUploader(IEnumerable<IFormFile> files)
        {
            if (!files.Any() || files.Single().Length == 0)
            {
                ViewBag.ErrorMessage = "File failed to load, please try again";
                return View();
            }
            else
            {
                IFormFile formFile = files.Single();
                ContentDispositionHeaderValue fileContent = ContentDispositionHeaderValue.Parse(formFile.ContentDisposition);
                string fileName = Path.GetFileName(fileContent.FileName.ToString().Trim('"'));

                string filePath = Path.Combine(Path.GetTempPath(), fileName);

                if (System.IO.File.Exists(filePath))
                    System.IO.File.Delete(filePath);

                using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
                {
                    formFile.CopyTo(fileStream);
                }

                return await LoadFile(new FileInfo(filePath));
            }
        }

        private async Task<IActionResult> LoadFile(FileInfo selectedFile)
        {
            if (selectedFile.Extension.ToUpper() == ".CSV") //not necessary as already filtering...
            {
                //use the CSVReader to read in the data
                string message;
                DataTable dataTable = CSVConverter.CSVDataToDataTable(selectedFile.OpenRead(), System.Threading.Thread.CurrentThread.CurrentCulture);

                if (dataTable == null) //then failed to be read
                {
                    message = "The CSV data needs to be in the correct format.";
                }
                else //got datatable but need to check
                {
                    message = dataTable.CheckDataTable();
                }

                if (message == null)
                {
                    //save in database
                    await SaveDatasetToDatabase(selectedFile.Name, dataTable);

                    try //to delete but if fails doesn't matter
                    {
                        System.IO.File.Delete(selectedFile.FullName);
                    }
                    catch (IOException)
                    {
                        //ignore error
                    }

                    TempData["InfoMessage"] = "File imported successfully!";
                }
                else
                {
                    TempData["ErrorMessage"] = message;
                }

                return RedirectToAction("Index"); //return to file loader/loaded files display screen
            }
            else if (selectedFile.Extension.ToUpper() == ".XLS" || selectedFile.Extension.ToUpper() == ".XLSX") //excel
            {
                System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

                //read in xls file
                using (FileStream stream = selectedFile.OpenRead())
                {
                    using (IExcelDataReader excelReader = ExcelReaderFactory.CreateReader(stream))
                    {
                        DataSet excelDataSet = excelReader.AsDataSet(new ExcelDataSetConfiguration() { ConfigureDataTable = (_) => new ExcelDataTableConfiguration() { UseHeaderRow = true } });

                        //if there is more than one worksheet then ask the user which sheet they want, otherwise automatically load it
                        if (excelDataSet.Tables.Count == 0)
                        {
                            TempData["ErrorMessage"] = "Error reading file. No sheets with valid data could be found in the Excel workbook.";
                            return RedirectToAction("Index");
                        }
                        else if (excelDataSet.Tables.Count == 1) //one excel sheet
                        {
                            DataTable dataTable = excelDataSet.Tables[0];
                            string message = dataTable.CheckDataTable();

                            if (message == null)
                            {
                                //save in database
                                await SaveDatasetToDatabase(selectedFile.Name, dataTable);

                                try //to delete...
                                {
                                    System.IO.File.Delete(selectedFile.FullName);
                                }
                                catch (IOException)
                                {
                                    //...if fails doesn't matter
                                }

                                TempData["InfoMessage"] = "File imported successfully!";
                            }
                            else
                            {
                                TempData["ErrorMessage"] = message;
                            }

                            return RedirectToAction("Index"); //return to file loader/loaded files display screen
                        }
                        else //more than 1 excel sheet
                        {
                            List<string> tableNames = new List<string>();
                            foreach (DataTable t in excelDataSet.Tables)
                            {
                                tableNames.Add(t.TableName);
                            }

                            TempData["TableNames"] = tableNames;
                            return RedirectToAction("SheetSelector", new { filename = selectedFile.FullName }); //go to sheet selection screen
                        }
                    }
                }
            }
            else
            {
                throw new ArgumentException("File format not recognised.");
            }
        }

        private async Task SaveDatasetToDatabase(string fileName, DataTable dataTable)
        {
            //get last version no based on existing dataset names
            int lastVersionNo = await repository.GetLastVersionNumberForDataset(fileName);
            Dataset dataset = dataTable.GetDataset(fileName, lastVersionNo);

            await repository.CreateDataset(dataset);
        }


        [HttpGet]
        public ActionResult SheetSelector(string fileName)
        {
            ViewBag.FileName = fileName;
            ViewBag.SheetList = TempData["TableNames"];

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SheetSelector(string sheetSelection, string fileName)
        {
            FileInfo selectedFile = new FileInfo(fileName);

            //get the correct datatable out the excel file (again)
            using (FileStream stream = selectedFile.OpenRead())
            {
                using (IExcelDataReader excelReader = ExcelReaderFactory.CreateReader(stream))
                {
                    DataSet excelDataSet = excelReader.AsDataSet(new ExcelDataSetConfiguration() { ConfigureDataTable = (_) => new ExcelDataTableConfiguration() { UseHeaderRow = true } });

                    //save to database
                    DataTable dataTable = excelDataSet.Tables[sheetSelection];
                    string message = dataTable.CheckDataTable();

                    if (message == null) //save to database
                    {
                        string datasetName = selectedFile.Name + " [" + sheetSelection + "]";
                        await SaveDatasetToDatabase(datasetName, dataTable);

                        try //to delete...
                        {
                            System.IO.File.Delete(selectedFile.FullName);
                        }
                        catch (IOException)
                        {
                            //if fails doesn't matter
                        }

                        TempData["InfoMessage"] = "File imported successfully!";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = message;
                    }
                }
            }

            //return to file upload/display page
            return RedirectToAction("Index");
        }

        [HttpDelete]
        public async Task<JsonResult> Destroy(int datasetID)
        {
            await repository.DeleteDataset(datasetID);
            return Json(true);
        }

        [HttpPost]
        public async Task<JsonResult> DeleteSelected(IEnumerable<int> datasetIDs)
        {
            await repository.DeleteDatasets(datasetIDs);
            return Json(true);
        }

SilveR/Controllers/UserOptionsController.cs
using Microsoft.AspNetCore.Mvc;
using SilveR.Models;
using SilveR.Services;
using System;
using System.Threading.Tasks;

namespace SilveR.Controllers
{
    public class UserOptionsController : Controller
    {
        private readonly ISilveRRepository repository;

        public UserOptionsController(ISilveRRepository repository)
        {
            this.repository = repository;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            UserOption options = await repository.GetUserOptions();
            return View(options);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUserOptions(UserOption userOption, string submitButtonValue)
        {
            if (submitButtonValue == "save")
            {
                await repository.UpdateUserOptions(userOption);
                return RedirectToAction("Index", "Home");
            }
            else if (submitButtonValue == "reset")
            {
                await repository.ResetUserOptions(userOption); //remove the useroptions

                return RedirectToAction ("Index");
            }
            else
                throw new ArgumentException("submitButtonValue is not valid!");
        }
    }
}

SilveR/Views/Shared/AnalysisErrors.cshtml
@if (ViewContext.ViewData.ModelState.IsValid == false)
{
    <div class="alert alert-danger alert-dismissable fade show">
        <button class="close" data-dismiss="alert" type="button"><span>&times;</span></button>
        <strong>Error!</strong>
        <br />
        <div id="errorsList">@Html.ValidationSummary(false)</div>
    </div>
}
else if (ViewBag.WarningMessages != null)
{
    <div class="alert alert-warning alert-dismissable fade show">
        <button class="close" data-dismiss="alert" type="button"><span>&times;</span></button>
        <strong>Warning!</strong>
        <br />
        <div id="warningsList">
            @foreach (string warningMessage in ViewBag.WarningMessages)
            {
                <p>@warningMessage</p>
            }
        </div>
        <br />
        <button class="btn btn-warning" name="ignoreWarnings" type="submit" value="true">Submit Anyway</button>
    </div>
}

SilveR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Program.AppName</title>

    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/kendo-ui/styles/kendo.common.min.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/kendo-ui/styles/kendo.bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />

    <!-- Insert this line above script imports  -->
    <script>if (typeof module === 'object') { window.module = module; module = undefined; }</script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/kendo-ui/js/kendo.custom.min.js"></script>

    <environment names="Development">
        <script defer src="~/js/index.js"></script>
    </environment>
    <environment names="Production">
        <script defer src="~/js/index.min.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
</head>
<body>
    <noscript>
        <div class="noscript-warning">
            This site will not function correctly with JavaScript disabled. Please re-enable JavaScript in your browser and try again.
            To enable Javascript follow this link http://enable-javascript.com/.
        </div>
    </noscript>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">@Program.AppName</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Data" asp-action="Index">My Data</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link text-dark dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">Statistics</a>

                        <ul class="nav-item dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="SummaryStatistics">Summary Statistics</a></li>

                            <li class="dropdown-submenu">
                                <a class="dropdown-item dropdown-toggle" data-toggle="dropdown" href="#">Parametric Analysis</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="SingleMeasuresParametricAnalysis">Single Measures Parametric Analysis</a></li>
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="RepeatedMeasuresParametricAnalysis">Repeated Measures Parametric Analysis</a></li>

                                    <li class="dropdown-submenu">
                                        <a class="dropdown-item dropdown-toggle" data-toggle="dropdown" href="#">P-value Adjustment</a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="PValueAdjustmentUserBasedInputs">User Based Inputs</a></li>
                                            <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="PValueAdjustmentDatasetBasedInputs">Dataset Based Inputs</a></li>
                                        </ul>
                                    </li>

                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="PairedTTestAnalysis">Paired t-test Analysis and Within-subject Analysis</a></li>
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="UnpairedTTestAnalysis">Unpaired t-test Analysis</a></li>
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="CorrelationAnalysis">Correlation Analysis</a></li>
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="LinearRegressionAnalysis">Linear Regression Analysis</a></li>
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="DoseResponseAndNonLinearRegressionAnalysis">Dose-response and Non-linear Regression Analysis</a></li>
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="OneSampleTTestAnalysis">One-sample t-test Analysis</a></li>
                                </ul>
                            </li>

                            <li class="dropdown-submenu">
                                <a class="dropdown-item dropdown-toggle" data-toggle="dropdown" href="#">Additional Analysis</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="NonParametricAnalysis">Non-parametric Analysis</a></li>
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="ChiSquaredAndFishersExactTest">Chi-squared and Fisher's Exact Test</a></li>
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="SurvivalAnalysis">Survival Analysis</a></li>
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="MultivariateAnalysis">Multivariate Analysis</a></li>
                                </ul>
                            </li>

                            <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="GraphicalAnalysis">Graphical Analysis</a></li>

                            <li class="dropdown-submenu">
                                <a class="dropdown-item dropdown-toggle" data-toggle="dropdown" href="#">Power Analysis</a>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-submenu">
                                        <a class="dropdown-item dropdown-toggle" data-toggle="dropdown" href="#">Comparison of Means</a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="ComparisonOfMeansPowerAnalysisUserBasedInputs">User based inputs</a></li>
                                            <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="ComparisonOfMeansPowerAnalysisDatasetBasedInputs">Dataset based inputs</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a class="dropdown-item dropdown-toggle" data-toggle="dropdown" href="#">One-way ANOVA</a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="OneWayANOVAPowerAnalysisUserBasedInputs">User based inputs</a></li>
                                            <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="OneWayANOVAPowerAnalysisDatasetBasedInputs">Dataset based inputs</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>

                            <li class="dropdown-submenu">
                                <a class="dropdown-item dropdown-toggle" data-toggle="dropdown" href="#">Unvalidated Analysis</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="NestedDesignAnalysis">Nested Design Analysis</a></li>
                                    <li><a class="dropdown-item" asp-controller="Analyses" asp-action="AnalysisDataSelector" asp-route-analysisName="IncompleteFactorialParametricAnalysis">Incomplete Factorial Parametric Analysis</a></li>
                                </ul>
                            </li>
                        </ul>

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Analyses" asp-action="Index">My Analyses</a>
                    </li>
                </ul>
            </div>

            <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="UserOptions" asp-action="Index"><i class="fa fa-lg fa-gears"></i></a>
                    <li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content" style="margin-top:70px">
        @RenderBody()
    </div>
</body>
</html>